### ISSUE TITLE
Causes Unable to build shared access signature from given values exception

### ISSUE THREAD

**Issue by qawnaoya** [Azure-Samples/azure-iot-samples-python#22]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
python SimulatedDevice.py

### Any log messages given by the failure
IoT Hub Quickstart #1 - Simulated device
Press Ctrl-C to exit
2020-02-13 14:42:27,776 [INFO   ] (__init__) Using Shared Key authentication for {IPRHUB.azure-devices.net, M5TEST, None}
2020-02-13 14:42:27,777 [DEBUG  ] (wrapper) Starting run_op in pipeline thread
2020-02-13 14:42:27,777 [DEBUG  ] (_get_named_executor) Creating pipeline executor
2020-02-13 14:42:27,778 [INFO   ] (generate_new_sas_token) Generating new SAS token for (M5TEST,None) that expires 3600 seconds in the future
2020-02-13 14:42:27,779 [ERROR  ] (run_op) Unexpected error in <azure.iot.device.iothub.pipeline.pipeline_stages_iothub.UseAuthProviderStage object at 0x7f9848fec890>._run_op() call
Traceback (most recent call last):
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/sk_authentication_provider.py", line 114, in _sign
    signing_key = base64.b64decode(self.shared_access_key.encode("utf-8"))
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/base64.py", line 87, in b64decode      return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 101, in run_op
    self._run_op(op)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/pipeline/pipeline_stages_iothub.py", line 49, in _run_op
    sas_token=self.auth_provider.get_current_sas_token(),
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/base_renewable_token_authentication_provider.py", line 224, in get_current_sas_token
    self.generate_new_sas_token()
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/base_renewable_token_authentication_provider.py", line 127, in generate_new_sas_token
    signature = self._sign(quoted_resource_uri, expiry)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/sk_authentication_provider.py", line 118, in _sign
    raise ValueError("Unable to build shared access signature from given values")
ValueError: Unable to build shared access signature from given values
2020-02-13 14:42:27,821 [ERROR  ] (complete) SetAuthProviderOperation: completing with error Unable to build shared access signature from given values
2020-02-13 14:42:27,821 [DEBUG  ] (wrapper) Starting <azure.iot.device.common.evented_callback.EventedCallback object at 0x7f9848fec6d0> in callback thread
2020-02-13 14:42:27,821 [DEBUG  ] (_get_named_executor) Creating callback executor
2020-02-13 14:42:27,822 [ERROR  ] (wrapping_callback) Callback completed with error Unable to build shared access signature from given values
Traceback (most recent call last):
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/sk_authentication_provider.py", line 114, in _sign
    signing_key = base64.b64decode(self.shared_access_key.encode("utf-8"))
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/base64.py", line 87, in b64decode      return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 101, in run_op
    self._run_op(op)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/pipeline/pipeline_stages_iothub.py", line 49, in _run_op
    sas_token=self.auth_provider.get_current_sas_token(),
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/base_renewable_token_authentication_provider.py", line 224, in get_current_sas_token
    self.generate_new_sas_token()
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/base_renewable_token_authentication_provider.py", line 127, in generate_new_sas_token
    signature = self._sign(quoted_resource_uri, expiry)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/sk_authentication_provider.py", line 118, in _sign
    raise ValueError("Unable to build shared access signature from given values")
ValueError: Unable to build shared access signature from given values
Traceback (most recent call last):
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/sk_authentication_provider.py", line 114, in _sign
    signing_key = base64.b64decode(self.shared_access_key.encode("utf-8"))
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/base64.py", line 87, in b64decode      return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SimulatedDevice.py", line 64, in <module>
    iothub_client_telemetry_sample_run()
  File "SimulatedDevice.py", line 31, in iothub_client_telemetry_sample_run
    client = iothub_client_init()
  File "SimulatedDevice.py", line 25, in iothub_client_init
    client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING)
  File "<string>", line 1, in create_from_connection_string
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/abstract_clients.py", line 74, in create_from_connection_string
    http_pipeline = pipeline.HTTPPipeline(authentication_provider, pipeline_configuration)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/pipeline/http_pipeline.py", line 61, in __init__
    callback.wait_for_completion()
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/common/evented_callback.py", line 70, in wait_for_completion
    raise self.exception
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 101, in run_op
    self._run_op(op)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/pipeline/pipeline_stages_iothub.py", line 49, in _run_op
    sas_token=self.auth_provider.get_current_sas_token(),
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/base_renewable_token_authentication_provider.py", line 224, in get_current_sas_token
    self.generate_new_sas_token()
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/base_renewable_token_authentication_provider.py", line 127, in generate_new_sas_token
    signature = self._sign(quoted_resource_uri, expiry)
  File "/home/nikeda/.pyenv/versions/anaconda3-2019.07/envs/azure-iot/lib/python3.7/site-packages/azure/iot/device/iothub/auth/sk_authentication_provider.py", line 118, in _sign
    raise ValueError("Unable to build shared access signature from given values")
ValueError: Unable to build shared access signature from given values

### Expected/desired behavior
>

### OS and Version?
Windows 10 and Ubuntu 18.04 on WSL

### Versions
10.0.18363.657

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create an issue on [azure-iot-sdk-python](https://github.com/Azure/azure-iot-sdk-python) if needed.
