### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by shivanjalikhare** [Azure-Samples/azure-iot-samples-python#27]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> git clone the repository

### Any log messages given by the failure
Traceback (most recent call last):
  File "C:\Users\shivi\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\shivi\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\shivi\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy\launcher\__main__.py", line 95, in <module>
    main()
  File "c:\Users\shivi\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy\launcher\__main__.py", line 51, in main
    launcher.connect(host, port)
  File "c:\Users\shivi\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy\launcher/../..\debugpy\launcher\__init__.py", line 34, in connect
    sock.connect((host, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### Expected/desired behavior
Successful Connection to IoT hub

### OS and Version?
> Windows10.
### Versions
> .NET Runtime: 2.1.812
Python 3.6.3

### Mention any other details that might be useful
I tried running simulatedDevice.py and was successful. But when i tried again today, I am getting this error.

How should this be handled?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create an issue on [azure-iot-sdk-python](https://github.com/Azure/azure-iot-sdk-python) if needed.
